spring:
  application:
    name: websocket-alerts

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: websocket-alerts
      auto-offset-reset: latest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.sudhird.risk.websocket_alerts.model.RiskDecisionEvent
        spring.json.trusted.packages: "*"

server:
  port: 8082